### ISSUE TITLE
Look into SQLite + Bookshelf.js as alternative to LevelDB

### ISSUE THREAD

**Issue by danburzo** [danburzo/every-street#6]

**Comment by Penagwin** [comment]
Based off performance data from https://leveldb.googlecode.com/svn/trunk/doc/benchmark.html
I don't think sqllite would be the best option. I think we may want to look at something such as Redis for speed.

**Comment by danburzo** [comment]
Yikes, sqlite looks pretty bad in those benchmarks. Closing this, filing under _nevermind_ :)
